CREATE TABLE users (
    is_active BOOLEAN NOT NULL,
    is_blocked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    phone VARCHAR(15),
    username VARCHAR(100) NOT NULL,
    blocked_reason VARCHAR(255),
    business_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    firebase_uid VARCHAR(255) NOT NULL UNIQUE,
    refresh_token VARCHAR(255),
    role VARCHAR(255) NOT NULL CHECK (role IN ('STUDENT', 'MERCHANT', 'ADMIN')),
    student_id VARCHAR(255) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE wallets (
    balance NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    user_id BIGINT NOT NULL UNIQUE,
    version BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE cards (
    is_active BOOLEAN NOT NULL,
    is_blocked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    deactivated_at TIMESTAMP(6),
    deactivated_by_user_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    last_used_at TIMESTAMP(6),
    linked_at TIMESTAMP(6),
    user_id BIGINT,
    card_uid VARCHAR(50) NOT NULL UNIQUE,
    blocked_reason VARCHAR(255),
    deactivated_reason VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE payments (
    amount NUMERIC(38, 2) NOT NULL,
    refunded_amount NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    merchant_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_payments_merchant FOREIGN KEY (merchant_id) REFERENCES users (id),
    CONSTRAINT fk_payments_student FOREIGN KEY (student_id) REFERENCES users (id)
);

CREATE TABLE recharge_orders (
    amount NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    razorpay_order_id VARCHAR(255) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    receipt_id VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_recharge_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE wallet_transactions (
    amount NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    wallet_id BIGINT NOT NULL,
    direction VARCHAR(20) NOT NULL CHECK (direction IN ('CREDIT', 'DEBIT')),
    card_uid VARCHAR(50),
    status VARCHAR(50),
    transaction_category VARCHAR(50),
    counterparty_name VARCHAR(255),
    reference VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_wallet_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);
